### ISSUE TITLE
needs more robots

### ISSUE THREAD

**Issue by chrisvdp** [sgoreczky/sgoreczky.github.io#2]
see title

**Comment by sgoreczky** [comment]
Completely agree with this issue. It's a P0.

**Comment by chrisvdp** [comment]
oh no https://github.com/sgoreczky/sgoreczky.github.io/blob/50c35bd32035ebbc9160176c64052842aad9e397/index.html#L63

**Comment by sgoreczky** [comment]
@chrisvdp Robot has been re-added, what do you think?

**Comment by chrisvdp** [comment]
very nice
